---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  scss-lint:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
  markdownlint:
    enabled:
ratings:
   paths:
   - "**.js"
exclude_paths:
- .node_modules/
