nginx:
    build: ./nginx
    container_name: ms_nginx
    links:
        - "petstore:petstore"
    ports:
        - "80:80"

petstore:
    build: ./petstore
    container_name: ms_petstore
    links:
        - "mongo:mongo"
    volumes:
        - "./petstore:/src/app"
    working_dir: "/src/app"
    ports:
        - "8080:8080"
    command: npm start

mongo:
    container_name: ms_mongo
    image: mongo:latest
    environment:
        - loglevel=1
    ports:
        - "27017:27017"
