nginx:
  build: ./nginx
  container_name: ms_nginx
  links:
    - "petstore:petstore"
  ports:
    - "80:80"
    
petstore:
  build: ./petstore
  container_name: ms_petstore
  volumes:
    - "./app:/src/app"
  ports:
    - "8080:8080"
  command: npm start
