express:
    port: 8080

auth:
    jwt_secret: 'UR4swimlane$'

spec:
    petstore: 'http://petstore.swagger.io/v2/swagger.json'

mongo:
    url: 'mongodb://mongo:27017'

# none/debug/info
loglevel: none
